### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by dpriver** [LibreLabUCM/TelegMineCraftBot#1]
This guy has some good links
[ComputerCraft lua stuff](http://www.planetminecraft.com/blog/computer-craft-tutorials---lua/)

**Comment by DevPGSV** [comment]
@Kuronogard Also:
http://www.computercraft.info/wiki/HTTP_(API)

**Comment by Akronix** [comment]
What about using a wiki page to gather all the documentation there, instead of this issue?

There's also a book for learning Lua called: "Beginning Lua programming". [It's available for free for UCM students through safari books.](http://cisne.sim.ucm.es/record=b2738778~S6*spi)
